server:
  port: ${PORT:8080}

spring:
  application:
    name: land

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.tozpptsgpodiwnsyxzde}
    password: ${SPRING_DATASOURCE_PASSWORD:A0ZwvI5DKYgFeSPs}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      url: ${REDIS_URL:rediss://default:gQAAAAAAAan-AAIgcDE5NGMwMWJiY2Q0NDU0YWFjYjFkNzllYTY4YzVhMWM0Mw@champion-koi-109054.upstash.io:6379}
      ssl:
        enabled: true

nomba:
  api:
    base-url: https://api.nomba.com
    account-id: ${NOMBA_ACCOUNT_ID:f666ef9b-888e-4799-85ce-acb505b28023}
    client-key: ${NOMBA_CLIENT_KEY:e5e85b13-f560-4643-814e-c87435dbbc15}
    secret-key: ${NOMBA_SECRET_KEY:8/doS7Q3w77EANpk3vpgSrc05hhOiRWp3eBs01sXyZ1AmovtZUXlmrxie+xnEF2tR4q79t0IFufMD1d4JrkT8g==}
    sub-account-id: ${NOMBA_SUB_ACCOUNT_ID:5a6c217c-010f-4c90-9517-382c9ec46595}
