server:
  port: 8080

spring:
  application:
    name: land
  
  datasource:
    url: jdbc:postgresql://localhost:5432/autocollect_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

nomba:
  api:
    base-url: https://api.nomba.com
    account-id: "f666ef9b-888e-4799-85ce-acb505b28023"
    client-key: "e5e85b13-f560-4643-814e-c87435dbbc15"
    secret-key: "8/doS7Q3w77EANpk3vpgSrc05hhOiRWp3eBs01sXyZ1AmovtZUXlmrxie+xnEF2tR4q79t0IFufMD1d4JrkT8g=="
    sub-account-id: "5a6c217c-010f-4c90-9517-382c9ec46595"
